//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis_Barberia.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barberos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Barberos()
        {
            this.Servicios_Prestados = new HashSet<Servicios_Prestados>();
        }
    
        public int Barbero_Id { get; set; }
        public string Nombre_Barberos { get; set; }
        public string Apellido_Barberos { get; set; }
        public short Edad_Barberos { get; set; }
        public string Domicilio_Barberos { get; set; }
        public System.DateTime Fecha_Contrato { get; set; }
        public string Telefono_Barberos { get; set; }
        public string Instagram_Barberos { get; set; }
        public string Facebook_Barberos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios_Prestados> Servicios_Prestados { get; set; }
    }
}
