//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis_Barberia.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Clientes()
        {
            this.Servicios_Prestados = new HashSet<Servicios_Prestados>();
            this.Turno = new HashSet<Turno>();
        }
    
        public int Cliente_id { get; set; }
        public string Nombre_Clientes { get; set; }
        public string Apellido_Clientes { get; set; }
        public short Edad_Clientes { get; set; }
        public string Domicilio_Clientes { get; set; }
        public string Telefono { get; set; }
        public string Instagram { get; set; }
        public string Facebook { get; set; }
        public Nullable<short> Cantidad { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servicios_Prestados> Servicios_Prestados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Turno> Turno { get; set; }
    }
}
