//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tesis_Barberia.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios_Prestados
    {
        public int ServicioPrestado_Id { get; set; }
        public int Barbero_Id { get; set; }
        public int Cliente_Id { get; set; }
        public int TipoDePago_Id { get; set; }
        public int TipoDeServicio_Id { get; set; }
        public System.DateTime FechaRealizacion { get; set; }
        public double Total { get; set; }
    
        public virtual Barberos Barberos { get; set; }
        public virtual Clientes Clientes { get; set; }
        public virtual TipoDePago TipoDePago { get; set; }
        public virtual TipoDeServicio TipoDeServicio { get; set; }
    }
}
